### ISSUE TITLE
Window git clone invalid path error

### ISSUE THREAD

**Issue by igiza1213** [SRHS-SPAM/backend_assignment#2]
## 문재
Window 환경에서 git clone시 
1/hyunseo/이런식으로 작성하면 돼요.
파일의 인코딩이 깨져서 clone작업이 진행되지 않습니다.

## 해결방법
디렉토리로 이동 후
```bash
git config core.protectNTFS false
git checkout -f HEAD```
작성

혹은 파일 삭제 || 이름 변경

**Comment by igiza1213** [comment]
@3boku

**Comment by 3boku** [comment]
감사합니다. README.md에 옮겨주시고, PR 올려주시면 감사하겠습니다.
해당 이슈는 닫겠습니다.
